[package]
name = "sparse_set"
version = "0.1.0"
edition = "2021"
description = "Implementation of the sparse set data structure"
publish = false
readme = "README.md"

[dependencies]
arbitrary = { version = "1.1.3", optional = true }

[dev-dependencies]
coverage-helper = "0.1.0"
